#!/usr/bin/env python3
__version__ = "1.1.0"
"""dns monitoring and anomaly detection"""

import argparse
import json
import math
import os
import platform
import re
import signal
import subprocess
import sys
import time
from collections import defaultdict, deque
from datetime import datetime


class EntropyAnalyzer:
    """analyze string entropy for dga detection"""

    # character frequency in normal english domains
    NORMAL_FREQ = {
        'e': 0.127, 't': 0.091, 'a': 0.082, 'o': 0.075, 'i': 0.070,
        'n': 0.067, 's': 0.063, 'h': 0.061, 'r': 0.060, 'd': 0.043,
        'l': 0.040, 'c': 0.028, 'u': 0.028, 'm': 0.024, 'w': 0.024,
        'f': 0.022, 'g': 0.020, 'y': 0.020, 'p': 0.019, 'b': 0.015,
    }

    @staticmethod
    def shannon_entropy(text):
        """calculate shannon entropy of a string"""
        if not text:
            return 0.0
        freq = defaultdict(int)
        for c in text:
            freq[c] += 1
        length = len(text)
        entropy = 0.0
        for count in freq.values():
            p = count / length
            if p > 0:
                entropy -= p * math.log2(p)
        return entropy

    @classmethod
    def char_frequency_score(cls, text):
        """score based on deviation from normal character frequency"""
        if not text:
            return 0.0
        text = text.lower()
        freq = defaultdict(int)
        for c in text:
            if c.isalpha():
                freq[c] += 1
        total = sum(freq.values())
        if total == 0:
            return 0.0
        score = 0.0
        for char, count in freq.items():
            observed = count / total
            expected = cls.NORMAL_FREQ.get(char, 0.01)
            score += abs(observed - expected)
        return score

    @staticmethod
    def consonant_ratio(text):
        """ratio of consonants to vowels"""
        vowels = set("aeiou")
        text = text.lower()
        v_count = sum(1 for c in text if c in vowels)
        c_count = sum(1 for c in text if c.isalpha() and c not in vowels)
        if v_count == 0:
            return float(c_count) if c_count else 0.0
        return c_count / v_count

    @classmethod
    def is_dga(cls, domain, entropy_threshold=3.5, freq_threshold=0.6):
        """determine if a domain is likely generated by a dga"""
        parts = domain.split(".")
        if len(parts) < 2:
            return False, {}
        subdomain = parts[0]
        if len(subdomain) < 6:
            return False, {}
        entropy = cls.shannon_entropy(subdomain)
        freq_score = cls.char_frequency_score(subdomain)
        c_ratio = cls.consonant_ratio(subdomain)
        is_suspicious = (
            entropy >= entropy_threshold
            or freq_score >= freq_threshold
            or c_ratio > 5.0
        )
        details = {
            "entropy": round(entropy, 3),
            "freq_deviation": round(freq_score, 3),
            "consonant_ratio": round(c_ratio, 2),
            "subdomain_length": len(subdomain),
        }
        return is_suspicious, details


class QueryTracker:
    """track dns query rates per source"""

    def __init__(self, window=60, rate_limit=100):
        self.window = window
        self.rate_limit = rate_limit
        self.queries = defaultdict(deque)

    def record(self, src_ip, timestamp):
        """record a query and return current rate"""
        q = self.queries[src_ip]
        q.append(timestamp)
        cutoff = timestamp - self.window
        while q and q[0] < cutoff:
            q.popleft()
        return len(q)

    def is_excessive(self, src_ip, timestamp):
        """check if a source exceeds the rate limit"""
        rate = self.record(src_ip, timestamp)
        return rate >= self.rate_limit, rate

    def top_sources(self, n=10):
        """return top n sources by query count"""
        counts = {ip: len(q) for ip, q in self.queries.items()}
        return sorted(counts.items(), key=lambda x: x[1], reverse=True)[:n]


class TunnelDetector:
    """detect dns tunneling patterns"""

    def __init__(self, length_threshold=60, subdomain_threshold=10):
        self.length_threshold = length_threshold
        self.subdomain_threshold = subdomain_threshold
        self.subdomain_counts = defaultdict(set)

    def check(self, domain, src_ip):
        """check for tunneling indicators"""
        alerts = []
        if len(domain) > self.length_threshold:
            alerts.append({
                "type": "long_query",
                "domain": domain,
                "length": len(domain),
            })
        parts = domain.split(".")
        if len(parts) >= 3:
            base = ".".join(parts[-2:])
            self.subdomain_counts[base].add(parts[0])
            if len(self.subdomain_counts[base]) > self.subdomain_threshold:
                alerts.append({
                    "type": "excessive_subdomains",
                    "base_domain": base,
                    "unique_subdomains": len(self.subdomain_counts[base]),
                })
        # check for encoded data patterns (base64, hex)
        if len(parts) > 0:
            sub = parts[0]
            if re.match(r'^[a-f0-9]{20,}$', sub):
                alerts.append({"type": "hex_encoded", "domain": domain})
            elif re.match(r'^[A-Za-z0-9+/]{20,}={0,2}$', sub):
                alerts.append({"type": "base64_encoded", "domain": domain})
        return alerts


class DnsMonitor:
    """main dns monitoring engine"""

    def __init__(self, entropy_threshold=3.5, rate_limit=100,
                 tunnel_length=60):
        self.analyzer = EntropyAnalyzer()
        self.tracker = QueryTracker(rate_limit=rate_limit)
        self.tunnel = TunnelDetector(length_threshold=tunnel_length)
        self.entropy_threshold = entropy_threshold
        self.alerts = []
        self.total_queries = 0
        self.domain_counts = defaultdict(int)

    def process_query(self, src_ip, domain, timestamp=None):
        """analyze a single dns query"""
        timestamp = timestamp or time.time()
        self.total_queries += 1
        self.domain_counts[domain] += 1
        alerts = []

        # check dga
        is_dga, details = self.analyzer.is_dga(
            domain, self.entropy_threshold
        )
        if is_dga:
            alert = {
                "type": "dga_detected",
                "source": src_ip,
                "domain": domain,
                "severity": "high",
                "timestamp": datetime.fromtimestamp(timestamp).isoformat(),
                "details": details,
            }
            alerts.append(alert)

        # check rate
        excessive, rate = self.tracker.is_excessive(src_ip, timestamp)
        if excessive:
            alert = {
                "type": "high_query_rate",
                "source": src_ip,
                "rate": rate,
                "severity": "medium",
                "timestamp": datetime.fromtimestamp(timestamp).isoformat(),
            }
            alerts.append(alert)

        # check tunneling
        tunnel_alerts = self.tunnel.check(domain, src_ip)
        for ta in tunnel_alerts:
            alert = {
                "type": f"tunnel_{ta['type']}",
                "source": src_ip,
                "domain": domain,
                "severity": "high",
                "timestamp": datetime.fromtimestamp(timestamp).isoformat(),
                "details": ta,
            }
            alerts.append(alert)

        for alert in alerts:
            self.alerts.append(alert)
            self.print_alert(alert)
        return alerts

    def print_alert(self, alert):
        """display an alert"""
        sev = alert["severity"].upper()
        atype = alert["type"]
        src = alert["source"]
        if "domain" in alert:
            print(f"[{sev}] {atype}: {alert['domain']} from {src}")
        else:
            print(f"[{sev}] {atype} from {src}")

    def stats(self):
        """return monitoring statistics"""
        return {
            "total_queries": self.total_queries,
            "unique_domains": len(self.domain_counts),
            "total_alerts": len(self.alerts),
            "top_domains": sorted(
                self.domain_counts.items(),
                key=lambda x: x[1], reverse=True
            )[:20],
            "top_sources": self.tracker.top_sources(),
        }


def parse_tcpdump_dns(line):
    """extract dns query info from tcpdump output"""
    # match patterns like: 192.168.1.10.52341 > 8.8.8.8.53: ... A? example.com.
    ip_match = re.search(r'(\d+\.\d+\.\d+\.\d+)\.\d+ >', line)
    query_match = re.search(r'A\?\s+(\S+)', line)
    if ip_match and query_match:
        src_ip = ip_match.group(1)
        domain = query_match.group(1).rstrip(".")
        return src_ip, domain
    return None, None


def get_default_interface():
    """detect default network interface"""
    system = platform.system()
    try:
        if system == "Linux":
            result = subprocess.run(
                ["ip", "route", "show", "default"],
                capture_output=True, text=True, timeout=5
            )
            parts = result.stdout.split()
            if "dev" in parts:
                return parts[parts.index("dev") + 1]
        elif system == "Darwin":
            result = subprocess.run(
                ["route", "-n", "get", "default"],
                capture_output=True, text=True, timeout=5
            )
            for line in result.stdout.split("\n"):
                if "interface:" in line:
                    return line.split()[-1]
    except (subprocess.TimeoutExpired, OSError, IndexError):
        pass
    defaults = {"Linux": "eth0", "Darwin": "en0", "Windows": "Ethernet"}
    return defaults.get(system, "eth0")


def is_admin():
    """check for root/admin privileges"""
    if platform.system() == "Windows":
        try:
            import ctypes
            return ctypes.windll.shell32.IsUserAnAdmin() != 0
        except (AttributeError, OSError):
            return False
    return os.geteuid() == 0


def monitor_live(interface, monitor):
    """capture live dns traffic"""
    system = platform.system()
    if system == "Windows":
        print("tcpdump not available on windows", file=sys.stderr)
        print("use windump or tshark for live dns capture", file=sys.stderr)
        sys.exit(1)

    cmd = ["tcpdump", "-i", interface, "-nn", "-l", "port", "53"]
    proc = subprocess.Popen(
        cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True
    )

    def stop(sig, frame):
        proc.terminate()

    signal.signal(signal.SIGINT, stop)
    signal.signal(signal.SIGTERM, stop)

    for line in proc.stdout:
        src_ip, domain = parse_tcpdump_dns(line)
        if src_ip and domain:
            monitor.process_query(src_ip, domain)

    proc.wait()


def run_demo(monitor):
    """run demo analysis with sample dns queries"""
    import random
    print("running demo mode (no root privileges)")
    print("analyzing sample dns queries for anomalies...\n")

    normal_domains = [
        "google.com", "github.com", "stackoverflow.com", "python.org",
        "wikipedia.org", "amazon.com", "cloudflare.com", "mozilla.org",
        "reddit.com", "arxiv.org", "ubuntu.com", "kernel.org",
    ]
    dga_domains = [
        "xkjf8qmzpwvn3r.malware.net", "q9hx7bvmzt4kp2.evil.com",
        "rnvbx8kz3qfhwm.botnet.org", "zpqmkjx7vn4bhr.c2server.net",
    ]
    tunnel_domains = [
        "4a6f686e20446f65206a6f686e40656d61696c2e636f6d.data.evil.com",
        "U29tZSBzZWNyZXQgZGF0YSBlbmNvZGVkIGluIGJhc2U2NA.exfil.bad.org",
    ]
    sources = ["192.168.1.10", "192.168.1.20", "10.0.0.5", "172.16.0.100"]
    base_time = time.time() - 60

    for i in range(80):
        src = random.choice(sources)
        domain = random.choice(normal_domains)
        monitor.process_query(src, domain, base_time + i * 0.5)

    for domain in dga_domains:
        src = random.choice(sources)
        monitor.process_query(src, domain, base_time + 50)

    for domain in tunnel_domains:
        monitor.process_query("10.0.0.5", domain, base_time + 55)

    # simulate high rate from one source
    for i in range(120):
        monitor.process_query(
            "172.16.0.100",
            f"sub{i}.rapid-query.suspicious.com",
            base_time + 30 + i * 0.1
        )


def main():
    default_iface = get_default_interface()
    parser = argparse.ArgumentParser(description="dns monitoring and anomaly detection")
    parser.add_argument("-i", "--interface", default=default_iface,
                        help=f"network interface (default: {default_iface})")
    parser.add_argument("--entropy", type=float, default=3.5,
                        help="entropy threshold for dga detection")
    parser.add_argument("--rate-limit", type=int, default=100,
                        help="queries per minute before alerting")
    parser.add_argument("--tunnel-length", type=int, default=60,
                        help="domain length threshold for tunnel detection")
    parser.add_argument("-o", "--output", help="save alerts to json file")
    parser.add_argument("--demo", action="store_true",
                        help="run with sample demo data")
    args = parser.parse_args()

    monitor = DnsMonitor(
        entropy_threshold=args.entropy,
        rate_limit=args.rate_limit,
        tunnel_length=args.tunnel_length,
    )

    if args.demo or not is_admin():
        run_demo(monitor)
    else:
        print(f"dns monitor started on {args.interface}")
        print(f"entropy threshold: {args.entropy}")
        print(f"rate limit: {args.rate_limit} queries/min")
        print()

        try:
            monitor_live(args.interface, monitor)
        except KeyboardInterrupt:
            pass

    stats = monitor.stats()
    print("\n--- dns monitor summary ---")
    print(f"queries analyzed: {stats['total_queries']}")
    print(f"unique domains:   {stats['unique_domains']}")
    print(f"alerts raised:    {stats['total_alerts']}")

    if args.output:
        with open(args.output, "w") as f:
            json.dump({"stats": stats, "alerts": monitor.alerts}, f, indent=2)
        print(f"saved to {args.output}")


if __name__ == "__main__":
    main()
